version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartone_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - node
    networks:
      - smartone
    environment:
      - PHP_FPM_LISTEN=9000

  node:
    image: node:18
    container_name: smartone_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: tail -f /dev/null
    ports:
      - "5175:5175"
    networks:
      - smartone

  nginx:
    depends_on:
      - app
    image: nginx:alpine
    container_name: smartone_nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./ssl/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./ssl/selfsigned.key:/etc/ssl/private/selfsigned.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - smartone

  db:
    image: mysql:8.0
    container_name: smartone_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartone
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - smartone

networks:
  smartone:

volumes:
  dbdata:
