version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.4-fpm
    container_name: smartone_dev_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - node
    networks:
      - smartone_dev
    environment:
      - PHP_FPM_LISTEN=9000

  node:
    image: node:18
    container_name: smartone_dev_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: tail -f /dev/null
    ports:
      - "5177:5175"
    networks:
      - smartone_dev

  nginx:
    depends_on:
      - app
    image: nginx:alpine
    container_name: smartone_dev_nginx
    ports:
      - "8083:80"
    volumes:
      - .:/var/www
      - ./ssl/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./ssl/selfsigned.key:/etc/ssl/private/selfsigned.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - smartone_dev

  db:
    image: mysql:8.0
    container_name: smartone_dev_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartone_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata_dev:/var/lib/mysql
    networks:
      - smartone_dev

networks:
  smartone_dev:

volumes:
  dbdata_dev:
